// All strings with accented characters centralized here using unicode escapes
// This prevents the vite-plugin-singlefile from corrupting UTF-8 characters

export const S = {
  // Menu items
  prontuario: 'Prontu\u00e1rio',
  beneficiarios: 'Benefici\u00e1rios',
  beneficiario: 'Benefici\u00e1rio',
  voluntarios: 'Volunt\u00e1rios',
  voluntario: 'Volunt\u00e1rio',
  relatorios: 'Relat\u00f3rios',
  relatorio: 'Relat\u00f3rio',
  financeiro: 'Financeiro',
  profissionais: 'Profissionais',
  profissional: 'Profissional',
  inicio: 'In\u00edcio',
  
  // Buttons
  imprimir: 'Imprimir',
  salvar: 'Salvar',
  cancelar: 'Cancelar',
  editar: 'Editar',
  excluir: 'Excluir',
  adicionar: 'Adicionar',
  atualizar: 'Atualizar',
  fechar: 'Fechar',
  voltar: 'Voltar',
  enviar: 'Enviar',
  agendar: 'Agendar',
  
  // Labels
  evolucao: 'Evolu\u00e7\u00e3o',
  evolucoes: 'Evolu\u00e7\u00f5es',
  descricao: 'Descri\u00e7\u00e3o',
  funcao: 'Fun\u00e7\u00e3o',
  obrigatorio: 'obrigat\u00f3rio',
  opcoes: 'Op\u00e7\u00f5es',
  vinculo: 'V\u00ednculo',
  genero: 'G\u00eanero',
  diagnostico: 'Diagn\u00f3stico',
  restricao: 'Restri\u00e7\u00e3o',
  medicacao: 'Medica\u00e7\u00e3o',
  alergia: 'Alergia',
  endereco: 'Endere\u00e7o',
  responsavel: 'Respons\u00e1vel',
  telefone: 'Telefone',
  condicao: 'Condi\u00e7\u00e3o',
  inclusao: 'Inclus\u00e3o',
  nascimento: 'Nascimento',
  receita: 'Receita',
  despesa: 'Despesa',
  doacao: 'Doa\u00e7\u00e3o',
  subvencao: 'Subven\u00e7\u00e3o',
  servicos: 'Servi\u00e7os',
  categoria: 'Categoria',
  lancamento: 'Lan\u00e7amento',
  ausencia: 'Aus\u00eancia',
  presenca: 'Presen\u00e7a',
  frequencia: 'Frequ\u00eancia',
  constipacao: 'Constipa\u00e7\u00e3o',
  alimentacao: 'Alimenta\u00e7\u00e3o',
  observacoes: 'Observa\u00e7\u00f5es',
  cirurgias: 'Cirurgias',
  comorbidades: 'Comorbidades',
  anamnese: 'Anamnese',
  planejamento: 'Planejamento',
  desempenho: 'Desempenho',
  atividades: 'Atividades',
  agendado: 'Agendado',
  
  // Headers/Titles
  fichaRegistro: 'Ficha de Registro do Benefici\u00e1rio (FRB)',
  gestaoAmovin: 'Gest\u00e3o Amovin Integrado',
  dadosBeneficiario: 'DADOS DO BENEFICI\u00c1RIO',
  dadosResponsavel: 'DADOS DO RESPONS\u00c1VEL',
  perfilNecessidades: 'PERFIL E NECESSIDADES',
  historiaCli: 'Hist\u00f3ria Cl\u00ednica',
  saudeGeral: 'Sa\u00fade Geral',
  autonomiaAVD: 'Autonomia e Vida Di\u00e1ria (AVDs)',
  obsFamilia: 'Observa\u00e7\u00f5es da Fam\u00edlia',
  registroEvolucao: 'Registro de Evolu\u00e7\u00e3o de Atendimento',
  prontuarioMulti: 'Prontu\u00e1rio de Atendimento Multidisciplinar',
  termoAdesao: 'Termo de Ades\u00e3o',
  naoDefinido: 'n\u00e3o definido',
  semFoto: 'Sem foto',
  selecioneOpcao: 'Selecione...',
  
  // Misc
  sim: 'Sim',
  nao: 'N\u00e3o',
  naoTenhoCerteza: 'N\u00e3o tenho certeza',
  feminino: 'Feminino',
  masculino: 'Masculino',
  naoBinario: 'N\u00e3o-Bin\u00e1rio',
  prefiroNaoResponder: 'Prefiro n\u00e3o responder',
  mae: 'M\u00e3e',
  avo: 'Av\u00f3',
  tutorLegal: 'Tutor Legal',
};
